### PR TITLE
Clarification

### PR DESCRIPTION
**Pull request by MemeHoovy**

### CODE REVIEW

**Comment by Sylveondev** [comment]
Alr so the line edited is weird because that's the default when you run out of health.

**Comment by LEVIXDDLMAO** [comment]
> Alr so the line edited is weird because that's the default when you run out of health.

how did you like my icon remaster?

**Comment by MemeHoovy** [comment]
> Alr so the line edited is weird because that's the default when you run out of health.

yeah, but this is for when you button mash without ghost tapping

**Comment by Sylveondev** [comment]
oh kk my bad

**Comment by Sylveondev** [comment]
> > Alr so the line edited is weird because that's the default when you run out of health.
> 
> how did you like my icon remaster?

It was good

**Pull request merged**
